// 遵循MIT协议开源
setTimeout("text()","0"); 
function text() {
    var text=51;    //录入的数量 根据下面switch的内case的数量填写
    var number=Math.floor(Math.random()*text);    // 可均衡获取text数量的随机整数
    //根据函数number的随机整数查询相应的Text
    switch (number){
        case 0:text="落日归山海 山海藏深意";
        break;
        case 1:text="遗憾的是 未被坚定地选择过";
        break;
        case 3:text="日出了.....";
        break;
        case 4:text="赶在太阳升起之前 我们一起逃跑吧";
        break;
        case 5:text="错觉在于意识 想与不想";
        break;
        case 6:text="相遇不一定有结局 但一定有意义";
        break;
        case 7:text="青春是一时的 朋友是一辈子的";
        break;
        case 8:text="在宇宙中至死不渝";
        break;
        case 9:text="保持清醒 别迷失了自我";
        break;
        case 10:text="闯出自己的一片天地吧";
        break;
        case 11:text="她会消失 但她从未离去";
        break;
        case 12:text="不可能每天都是好日子";
        break;
        case 13:text="今晚月色真美";
        break;
        case 14:text="钟于 忠于 衷于 终于";
        break;
        case 15:text="到头来是一场空？";
        break;
        case 15:text="人会因为嘴硬失去很多东西吧";
        break;
        case 16:text="亿万人海中 你我相遇 是恩赐也是救赎";
        break;
        case 17:text="要永远相信光";
        break;
        case 18:text="万事都要全力以赴 包括开心";
        break;
        case 19:text="平安喜樂";
        break;
        case 20:text="向往自由";
        break;
        case 21:text="海的那边不一定是海";
        break;
        case 22:text="山的那边不一定是山";
        break;
        case 23:text="生活可以五颜六色 但不能乱七八糟";
        break;
        case 24:text="I am waiting.";
        break;
        case 25:text="若能避开猛烈的欢喜 自然不会有悲痛的袭来";
        break;
        case 26:text="哪有人会喜欢孤独 只是害怕失望罢了";
        break;
        case 27:text="相信奇迹 并创造奇迹";
        break;
        case 28:text="不会忘记的永远不会忘记 会忘记的留着也没有用";
        break;
        case 29:text="迷失的人迷失了 相逢的人会再相逢";
        break;
        case 30:text="死并非生的对立面 而作为生的一部分永存";
        break;
        case 31:text="最喜欢早上，好像什么都可以重新开始";
        break;
        case 32:text="以平凡开始 以平凡结束";
        break;
        case 33:text="死亡不是失去了生命 只是走出了时间";
        break;
        case 34:text="总会有一个人，山高路远，为你而来。";
        break;
        case 35:text="星河滚烫 你是人间理想";
        break;
        case 36:text="一起去啊 更远的地方";
        break;
        case 37:text="我生于长空，长于烈日 我翱翔于风，从未远去";
        break;
        case 38:text="跨过星河迈过月亮去迎接更好的自己";
        break;
        case 39:text="时间很贪婪";
        break;
        case 40:text="一个能升起月亮的身体 必然驮住了无数次日落";
        break;
        case 41:text="少年就是少年";
        break;
        case 42:text="据说，遇见即是上上签";
        break;
        case 43:text="万事皆有可能";
        break;
        case 44:text="原来有一天向日葵也会主动放弃太阳";
        break;
        case 45:text="天黑以后，往热闹地方躲，跟着别人努力快活，可惜心里头有定时的闹钟，提醒你有多寂寞。";
        break;
        case 46:text="唯有离别，才是人生";
        break;
        case 47:text="再来一万次，我也愿意伸手去捧水中碎月，一切都是虚的，但是没关系";
        break;
        case 48:text="遇事不决可问春风";
        break;
        case 49:text="如今你依旧是我的光";
        break;
        case 50:text="一心向往的梦之延续 又在何方";
        break;
        case 51:text="要在何时 才能解脱";
        break;
    }
    document.getElementById("yiyantext").innerHTML = text; // 在对应HTML元素显示输出的句子
    }
